### ISSUE TITLE
Update stable version in repo from 0.0.0 to 1.3.1

### ISSUE THREAD

**Issue by GermanBluefox** [Trixx34/ioBroker.soliscloud#28]
# Think about adding version 1.3.1 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**1.3.1** (30 days old)
**Installs**: stable=**0** (0%), latest=**8** (50%), total=**16**

Click to use [developer portal](https://www.iobroker.dev/adapter/soliscloud/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by Trixx34** [comment]
waiting for some feedback on version 1.4.0 to add to stable.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.3.1 but the current stable version is already 1.4.2.

So this issue should be closed.

@mcm1957 for evidence
